# 导航栏
menu_left:
  - title: 主页
    path: '' 
    icon_class: 'fa fa-home'
  - title: 归档
    path: 'archives'
    icon_class: 'fa fa-archive'
  - title: 关于
    path: /about
    icon_class: 'fa fa-user'

post_excerpt_paragraph: 1
max_excerpt_words: 500

menu_right:


search: 
  enable: true  # 是否使用搜索功能
  placeholder: 搜索

# 侧边栏展示的内容以及顺序
widgets_left:
  - category
widgets_right:
  - tag
  - recent
  - links


widgets_links:
  - title: github-xlee00
    url: https://github.com/xlee00
  - title: Hexo-xlee00
    url: https://xlee00.github.io/


# 默认情况下展示的分类，标签，最近的
# length 数目，超过部分折叠
# sort_by 排序依据
# rule 递增或递减
widgets_default_show:
  category:
    length: 15
    sort_by: length # length | name
    rule: desc      # desc | asc
  tag: 
    length: 50
    sort_by: name   # length | name
    rule: desc      # desc | asc
  recent:
    length: 10
    sort_by: date   # date | updated
    rule: desc      # desc | asc

# 是否使用 fancy | mathjax
fancybox: true
mathjax: true

# 备案号
beian: 无备案